providers:
- config:
    model_name: Llama-3-8B
    model_path: ../models/llama-3-8b
  name: llama_factory
  type: llama_factory
- config:
    model_name: phi-4-mini-flash-reasoning
    model_path: ../models/phi-4-mini-flash-reasoning
  name: phi_4_mini_flash_reasoning
  type: llama_factory
- config:
    model_name: liquid-ai-open-source
    model_path: ../models/liquid-ai-open-source
  name: liquid_ai
  type: llama_factory
- config:
    model_name: SmolLM3-3B
    model_path: ../models/smollm3-3b
  name: smollm3_3b
  type: llama_factory
- config:
    model_name: test-model
    model_path: ../models/test-model
  name: test_model
  type: llama_factory
# Hugging Face Providers
- config:
    model_name: LinWeizheDragon/ColBERT-v2
    model_type: retrieval
    device: auto
    trust_remote_code: true
  name: colbert_v2_retrieval
  type: huggingface
- config:
    model_name: gpt2
    model_type: causal
    device: auto
    trust_remote_code: true
  name: gpt2_generation
  type: huggingface
- config:
    model_name: t5-small
    model_type: seq2seq
    device: auto
    trust_remote_code: true
  name: t5_translation
  type: huggingface
- config:
    model_name: bert-base-uncased
    model_type: classification
    device: auto
    trust_remote_code: true
  name: bert_classification
  type: huggingface
- config:
    model_name: microsoft/DialoGPT-medium
    model_type: causal
    device: auto
    trust_remote_code: true
  name: dialogpt_chat
  type: huggingface
- config:
    model_name: facebook/bart-base
    model_type: seq2seq
    device: auto
    trust_remote_code: true
  name: bart_summarization
  type: huggingface
