# OpenTrustEval Security Configuration

authentication:
  # API Key settings
  api_key:
    enabled: true
    header_name: "X-API-Key"
    rate_limit_per_minute: 100
  
  # JWT settings
  jwt:
    enabled: true
    secret_key: "your-secret-key-change-this-in-production"
    algorithm: "HS256"
    expiration_hours: 24
  
  # Rate limiting
  rate_limiting:
    enabled: true
    max_attempts_per_minute: 5
    block_duration_minutes: 15
  
  # OAuth providers
  oauth:
    google:
      enabled: false
      client_id: ""
      client_secret: ""
      redirect_uri: "http://localhost:7863/auth/callback/google"
    
    github:
      enabled: false
      client_id: ""
      client_secret: ""
      redirect_uri: "http://localhost:7863/auth/callback/github"
    
    microsoft:
      enabled: false
      client_id: ""
      client_secret: ""
      redirect_uri: "http://localhost:7863/auth/callback/microsoft"
  
  # SAML providers
  saml:
    azure_ad:
      enabled: false
      entity_id: ""
      sso_url: ""
      x509_cert: ""
      attribute_mapping:
        email: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
        name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

security_monitoring:
  # Real-time monitoring
  real_time_monitoring:
    enabled: true
    check_interval_seconds: 30
  
  # Alert thresholds
  alert_thresholds:
    failed_auth_attempts: 5
    suspicious_ip_attempts: 10
    rate_limit_violations: 3
  
  # Blocking settings
  ip_blocking:
    enabled: true
    block_duration_minutes: 60
    max_blocked_ips: 1000
  
  # Logging
  logging:
    enabled: true
    log_file: "security_events.log"
    max_log_size_mb: 100
    backup_count: 5

secrets_management:
  # Encryption settings
  encryption:
    algorithm: "AES-256-GCM"
    key_derivation_iterations: 100000
  
  # Storage settings
  storage:
    type: "file"  # file, database
    path: "secrets/"
    backup_enabled: true
    backup_interval_hours: 24
  
  # Audit logging
  audit:
    enabled: true
    log_file: "secrets_audit.log"
    retention_days: 90
  
  # Secret policies
  policies:
    min_password_length: 12
    require_special_chars: true
    max_age_days: 365
    rotation_reminder_days: 30

dependency_scanning:
  # Vulnerability scanning
  vulnerability_scanning:
    enabled: true
    scan_interval_hours: 24
    sources:
      - "nvd"
      - "pyup"
  
  # License compliance
  license_compliance:
    enabled: true
    allowed_licenses:
      - "MIT"
      - "Apache-2.0"
      - "BSD-3-Clause"
      - "BSD-2-Clause"
      - "ISC"
      - "CC0-1.0"
  
  # Reporting
  reporting:
    enabled: true
    output_format: "json"  # json, csv, html
    include_fixed_versions: true
    include_cvss_scores: true

# Default users (for demo/testing)
default_users:
  - username: "admin"
    email: "admin@opentrusteval.com"
    role: "admin"
    permissions: ["read", "write", "delete", "admin"]
    password: "admin123"  # Change in production
  
  - username: "user"
    email: "user@opentrusteval.com"
    role: "user"
    permissions: ["read", "write"]
    password: "user123"  # Change in production 