name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install fastapi uvicorn[standard] pytest
      - name: Lint
        run: |
          pip install flake8
          flake8 .
      - name: Create .env file from secrets
        run: |
          echo "API_KEY=${API_KEY}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .env
          echo "GCP_SERVICE_ACCOUNT_JSON=${GCP_SERVICE_ACCOUNT_JSON}" >> .env
          echo "AZURE_CLIENT_ID=${AZURE_CLIENT_ID}" >> .env
          echo "AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}" >> .env
      - name: Run tests
        run: |
          pytest
      - name: Validate Data
        run: |
          python data_engineering/run_trust_scoring_system.py --test
      - name: Train and Evaluate Model
        run: |
          python scripts/train_and_evaluate.py
      - name: Generate Report
        run: |
          echo "CI Report" > ci_report.txt
          echo "=========" >> ci_report.txt
          echo "" >> ci_report.txt
          echo "Data Validation:" >> ci_report.txt
          cat data_engineering/test_reports/* >> ci_report.txt
          echo "" >> ci_report.txt
          echo "Model Evaluation:" >> ci_report.txt
          cat model_evaluation_report.txt >> ci_report.txt
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: ci-report
          path: ci_report.txt
